'use client';
import { useEffect, useState } from 'react';
import { Bell, ChevronDown, Swords, Trophy, Zap, Users } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import { getAnnouncements, getFriendsOnline, getLobbyDashboard, getOpenMatches, startRankedQueue } from '@/lib/services/lobby-service';
import { Announcement, FriendStatus, MatchmakingPreferences, OpenMatch, QueueState } from '@/lib/types/lobby';

const accent: Record<string,string> = { blue:'border-blue-500/50 hover:shadow-blue-500/20',green:'border-emerald-500/50',purple:'border-violet-500/50',gold:'border-amber-500/50' };

export default function LobbyPage(){
  const [data,setData]=useState<any>(null); const [matches,setMatches]=useState<OpenMatch[]>([]); const [friends,setFriends]=useState<FriendStatus[]>([]); const [ann,setAnn]=useState<Announcement[]>([]);
  const [queueState,setQueueState]=useState<QueueState>('idle'); const [prefs,setPrefs]=useState<MatchmakingPreferences>({subject:'Math',format:'1v1',matchLength:'Standard',ranked:true});
  const [showCustom,setShowCustom]=useState(false); const [joinTarget,setJoinTarget]=useState<OpenMatch|undefined>();
  useEffect(()=>{(async()=>{setData(await getLobbyDashboard()); setMatches(await getOpenMatches()); setFriends(await getFriendsOnline()); setAnn(await getAnnouncements());})();},[]);
  if(!data) return <div className='p-8'>Loading lobby...</div>;
  return <div className='min-h-screen bg-gradient-to-b from-slate-950 via-slate-950 to-indigo-950/40'>
    <nav className='sticky top-0 z-10 border-b border-slate-800/80 bg-slate-950/90 backdrop-blur px-4 py-3 flex items-center justify-between'><div className='flex items-center gap-8'><div className='font-semibold text-lg'>◆ ModuLeague</div><div className='hidden md:flex gap-6 text-sm'>{['Lobby','Ranked','Leaderboard','My Stats','Store'].map(t=><a key={t} className={t==='Lobby'?'text-blue-300 border-b border-blue-400 pb-1':'text-slate-300'}>{t}</a>)}</div></div><div className='flex items-center gap-4'><Bell className='w-4'/><div className='rounded-full bg-slate-700 w-8 h-8'/><div className='hidden sm:block'><p>{data.user.username}</p><p className='text-xs text-slate-400'>{data.user.currentRank}</p></div><ChevronDown className='w-4'/></div></nav>
    <main className='p-4 lg:p-6 grid grid-cols-1 xl:grid-cols-[270px_1fr_290px] gap-4'>
      <aside className='space-y-4'><div className='card p-4 space-y-2'>{['Find Match','Practice','Study Hub','Tournaments','Friends'].map((i)=><button key={i} className={`w-full text-left px-3 py-2 rounded ${i==='Find Match'?'bg-blue-600/20 text-blue-200':'hover:bg-slate-800'}`}>{i}</button>)}</div><div className='card p-4'><p className='text-xs text-violet-300'>{data.season.seasonLabel}</p><p className='font-semibold'>{data.season.passName}</p><p className='text-sm'>Level {data.season.level}</p><div className='h-2 bg-slate-800 rounded mt-2'><div style={{width:`${(data.season.xp/data.season.xpToNextLevel)*100}%`}} className='h-2 rounded bg-gradient-to-r from-blue-500 to-violet-500'/></div><button className='mt-3 text-sm w-full border border-slate-700 rounded py-2'>View Season Pass</button></div></aside>
      <section className='space-y-4'><div className='card p-5'><h1 className='text-2xl font-semibold'>Welcome back, {data.user.username}</h1><p className='text-slate-400'>Ready to climb the ranks? 4-match win streak active.</p></div>
      <div className='grid md:grid-cols-2 gap-4'>{data.modes.map((m:any)=><motion.button whileHover={{y:-3}} key={m.id} onClick={()=>m.id==='ranked'?setQueueState('selecting'):m.id==='custom'?setShowCustom(true):null} className={`card p-4 text-left border ${accent[m.accent]} transition`}><div className='flex justify-between'><h3 className='font-semibold'>{m.name}</h3>{m.id==='ranked'?<Swords/>:m.id==='practice'?<Trophy/>:m.id==='quick'?<Zap/>:<Users/>}</div><p className='text-sm text-slate-400 my-2'>{m.description}</p><p className='text-xs text-slate-300'>{m.subjectAvailability.join(' • ')}</p><p className='text-sm mt-3'>{m.playerCount.toLocaleString()} active</p></motion.button>)}</div>
      <div className='card p-4'><h2 className='font-semibold mb-3'>Open Matches</h2><div className='hidden md:block'>{matches.map(m=><div key={m.id} className='grid grid-cols-6 text-sm py-2 border-b border-slate-800'><span>{m.mode}</span><span>{m.players}/{m.maxPlayers}</span><span>{m.subject}</span><span>{m.matchType}</span><span>{m.createdAt}</span><button className='text-blue-300' onClick={()=>setJoinTarget(m)}>Join</button></div>)}</div><div className='md:hidden space-y-2'>{matches.map(m=><div className='p-3 rounded bg-slate-800/60' key={m.id}><p>{m.mode} • {m.subject}</p><button className='text-blue-300 text-sm' onClick={()=>setJoinTarget(m)}>Join</button></div>)}</div><button className='mt-3 w-full border border-slate-700 py-2 rounded'>Load More Matches</button></div>
      </section>
      <aside className='space-y-4'><div className='card p-4'><h3 className='font-semibold'>Your Rank</h3><div className='text-4xl my-2'>◈</div><p>{data.rank.currentRank} • {data.rank.skillRating} SR</p><p className='text-xs text-slate-400'>Next Rank: {data.rank.nextRank}</p></div><div className='card p-4'><h3 className='font-semibold'>Friends Online</h3>{friends.map(f=><div key={f.id} className='flex justify-between py-2 text-sm'><span>{f.username}</span><span className='text-slate-400'>{f.status}</span></div>)}<button className='w-full mt-2 border border-slate-700 rounded py-2 text-sm'>View All Friends</button></div><div className='card p-4'><h3 className='font-semibold'>Announcements</h3>{ann.map(a=><div key={a.id} className='py-2'><p className='text-sm'>{a.title}</p><p className='text-xs text-slate-400'>{a.description} • {a.timestamp}</p></div>)}</div></aside>
    </main>
    <AnimatePresence>{queueState==='selecting' && <div className='fixed inset-0 bg-black/60 grid place-items-center p-4'><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className='card p-5 w-full max-w-lg'><h3 className='font-semibold text-lg'>Find a Ranked Match</h3><p className='text-sm text-slate-400'>Ranked matches affect your Skill Rating. Accuracy is weighted most heavily, with speed as a secondary factor.</p><div className='mt-3 space-y-3'><select className='w-full bg-slate-800 p-2 rounded' value={prefs.subject} onChange={(e)=>setPrefs({...prefs,subject:e.target.value as any})}><option>Math</option><option>Reading & Writing</option><option>Mixed</option></select><select className='w-full bg-slate-800 p-2 rounded' value={prefs.format} onChange={(e)=>setPrefs({...prefs,format:e.target.value as any})}><option>1v1</option><option disabled>Team Match (Coming Soon)</option></select><select className='w-full bg-slate-800 p-2 rounded' value={prefs.matchLength} onChange={(e)=>setPrefs({...prefs,matchLength:e.target.value as any})}><option>Sprint</option><option>Standard</option><option>Full Arena</option></select></div><div className='mt-4 flex gap-2'><button onClick={async()=>{setQueueState('searching');await startRankedQueue(prefs);}} className='bg-blue-600 rounded px-4 py-2'>Start Queue</button><button onClick={()=>setQueueState('idle')} className='border rounded px-4 py-2'>Cancel</button></div></motion.div></div>}</AnimatePresence>
    <AnimatePresence>{queueState==='searching' && <div className='fixed inset-0 bg-black/60 grid place-items-center'><div className='card p-6 w-full max-w-md text-center'><p className='animate-pulse'>Searching for match...</p><p className='text-sm text-slate-400 mt-2'>{prefs.subject} • {prefs.format} • {prefs.matchLength} • ETA 00:35</p><button className='mt-4 border px-4 py-2 rounded' onClick={()=>setQueueState('cancelled')}>Cancel Queue</button></div></div>}</AnimatePresence>
    <AnimatePresence>{showCustom && <div className='fixed inset-0 bg-black/60 grid place-items-center'><div className='card p-6 max-w-md w-full'><h3 className='font-semibold'>Create Custom Match</h3><p className='text-sm text-slate-400'>Custom lobbies will connect to backend multiplayer sessions soon.</p><button className='mt-4 border px-4 py-2 rounded' onClick={()=>setShowCustom(false)}>Close</button></div></div>}</AnimatePresence>
    <AnimatePresence>{joinTarget && <div className='fixed inset-0 bg-black/60 grid place-items-center'><div className='card p-6 max-w-md w-full'><h3 className='font-semibold'>Join {joinTarget.mode}?</h3><p className='text-sm text-slate-400'>Backend realtime connection will be enabled in a future integration.</p><div className='flex gap-2 mt-4'><button className='bg-blue-600 px-4 py-2 rounded' onClick={()=>setJoinTarget(undefined)}>Confirm</button><button className='border px-4 py-2 rounded' onClick={()=>setJoinTarget(undefined)}>Cancel</button></div></div></div>}</AnimatePresence>
  </div>;
}
